export const AUTHORS_REPOSITORY = 'AUTHORS_REPOSITORY';
export const BOOKS_REPOSITORY = 'BOOKS_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const AUTHORS_BOOKS_REPOSITORY = 'AUTHORS_BOOKS_REPOSITORY';
export const AUTH_REPOSITORY = 'AUTH_REPOSITORY';
